In [1]:
import torch

In [2]:
torch.mps.is_available()

True

In [ ]:
torch.mps.device_count()

1

In [8]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2 = torch.tensor(arr)
arr2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
np.ones((1, 2))

array([[1., 1.]])

In [24]:
arr2.device

device(type='cpu')

In [27]:
arr2.to("mps")

tensor([[1, 2, 3],
        [4, 5, 6]], device='mps:0')