In [12]:
import torch

In [13]:
torch.mps.is_available()

True

Pattern 1: Creation from data

In [14]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

Pattern 2: Creation from a desired shape

In [15]:
shape = (2,3)
ones = torch.ones(shape)
zeroes = torch.zeros(shape)
random = torch.randn(shape)
print(ones)
print(zeroes)
print(random)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 0.4556, -1.4052, -1.7314],
        [ 1.7705,  0.7654,  0.1282]])


Pattern 3: Creation by mimicking another tensor

In [17]:
copy = torch.randn_like(tensor, dtype = torch.float)
copy

tensor([[0.4792, 0.3962, 0.7796],
        [0.6091, 1.0312, 0.2275]])

In [20]:
tensor.device
tensor.shape
tensor.dtype

torch.int64

AUTOGRAD

Data vs. Parameter

In [27]:
data = torch.tensor([[2,3,5,6,7], [8,6,5,4,3]])
parameter = torch.tensor(data, requires_grad = True, dtype = torch.float)
parameter


/var/folders/nq/n7zndp8x1g359khx0y0c0fn00000gn/T/ipykernel_96611/582676590.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  parameter = torch.tensor(data, requires_grad = True, dtype = torch.float)


tensor([[2., 3., 5., 6., 7.],
        [8., 6., 5., 4., 3.]], requires_grad=True)

Pytorch Computational Graph

In [28]:
a = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(3.0, requires_grad = True)
x = torch.tensor(4.0, requires_grad = True)

y = a + b
z = x * y
z

tensor(20., grad_fn=<MulBackward0>)

In [30]:
print(z.grad_fn)
print(y.grad_fn)
print(a.grad_fn)

None


In [37]:
# * vs @
# element wise multiplication (*) multiplies numbers in the same positions
# of course, the tensors must have the exact same shape

tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_b = torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor_a * tensor_b

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [43]:
# Matrix Multiplication (@)
# the number of columns in the first matrix must match the number of rows in the second matrix

tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype = torch.float)
tensor_b = torch.tensor([[1, 2, 3], [4, 5, 6], [4, 5, 6]], dtype = torch.float)

tensor_a @ tensor_b

#When we use this formula: Z = XW + b, we will always use the @ symbol

tensor([[21., 27., 33.],
        [48., 63., 78.]])

Reduction Operations

In [45]:
#sum(), mean(), min(), max()
# we can collapse with the specific dimension
# dim = 0 collapses vertically
# dim = 1 collapses horizontally

average_per_feature = tensor_b.mean(dim = 0)
average_per_row = tensor_b.mean(dim = 1)

print(average_per_feature)
print(average_per_row)

tensor([3., 4., 5.])
tensor([2., 5., 5.])


Selecting Data