In [29]:
import torch

In [ ]:
torch.mps.is_available()

True

Pattern 1: Creation from data

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor @ tensor.T

tensor([[14, 32],
        [32, 77]])

Pattern 2: Creation from a desired shape

In [ ]:
shape = (2,3)
ones = torch.ones(shape)
zeroes = torch.zeros(shape)
random = torch.randn(shape)
print(ones)
print(zeroes)
print(random)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 0.5152,  0.3809,  1.2755],
        [ 0.8959, -1.3428,  2.4478]])


Pattern 3: Creation by mimicking another tensor

In [ ]:
copy = torch.randn_like(tensor, dtype = torch.float)
copy

tensor([[-0.8251,  0.5033, -0.6749],
        [ 0.7927,  0.0573,  1.0335]])

In [ ]:
tensor.device
tensor.shape
tensor.dtype

torch.int64

AUTOGRAD

Data vs. Parameter

In [ ]:
data = torch.tensor([[2,3,5,6,7], [8,6,5,4,3]])
parameter = torch.tensor(data, requires_grad = True, dtype = torch.float)
parameter

/var/folders/nq/n7zndp8x1g359khx0y0c0fn00000gn/T/ipykernel_9815/2781831083.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  parameter = torch.tensor(data, requires_grad = True, dtype = torch.float)


tensor([[2., 3., 5., 6., 7.],
        [8., 6., 5., 4., 3.]], requires_grad=True)

Pytorch Computational Graph

In [ ]:
a = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(3.0, requires_grad = True)
x = torch.tensor(4.0, requires_grad = True)

y = a + b
z = x * y
z

tensor(20., grad_fn=<MulBackward0>)

In [ ]:
print(z.grad_fn)
print(y.grad_fn)
print(a.grad_fn)

None


In [ ]:
# * vs @
# element wise multiplication (*) multiplies numbers in the same positions
# of course, the tensors must have the exact same shape

tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_b = torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor_a * tensor_b

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [ ]:
# Matrix Multiplication (@)
# the number of columns in the first matrix must match the number of rows in the second matrix

tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype = torch.float)
tensor_b = torch.tensor([[1, 2, 3], [4, 5, 6], [4, 5, 6]], dtype = torch.float)

tensor_a @ tensor_b

#When we use this formula: Z = XW + b, we will always use the @ symbol

tensor([[21., 27., 33.],
        [48., 63., 78.]])

Reduction Operations

In [ ]:
#sum(), mean(), min(), max()
# we can collapse with the specific dimension
# dim = 0 collapses vertically
# dim = 1 collapses horizontally

average_per_feature = tensor_b.mean(dim = 0)
average_per_row = tensor_b.mean(dim = 1)

print(average_per_feature)
print(average_per_row)

tensor([3., 4., 5.])
tensor([2., 5., 5.])


Selecting Data

In [ ]:
x = torch.arange(12).reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
x[:,2] #give me all rows, but only the column at index 2 (the third column)

tensor([ 2,  6, 10])

In [ ]:
x[2,:]

tensor([ 8,  9, 10, 11])

In [ ]:
argmax = torch.argmax(x, dim = 1) #gives the highest number in each row
argmax

tensor([3, 3, 3])

In [ ]:
x[:,1]

tensor([1, 5, 9])

EXPERT SELECTION: TORCH.GATHER()

In [ ]:
data = torch.tensor([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

selected_indexes = torch.tensor([[2], [0], [2]])

selected_values = torch.gather(data, dim=1, index=selected_indexes)
selected_values

tensor([[3],
        [4],
        [9]])

SETUP

In [ ]:
N = 10

D_in = 1
D_out = 1

X = torch.randn(N, D_in)

true_w = torch.tensor([2.0])
true_b = torch.tensor(1.0)

y_true = true_w * X + true_b + torch.randn(N, D_in) * 0.1
y_true

tensor([[ 2.1366],
        [-0.3833],
        [ 0.3478],
        [ 1.3700],
        [ 5.6172],
        [ 3.6526],
        [ 0.3506],
        [-2.3106],
        [-2.3855],
        [ 0.0962]])

In [ ]:
W = torch.randn(D_in, D_out, requires_grad = True)
b = torch.randn(1, requires_grad = True)
print(w)
print(b)

tensor([[-0.0473]], requires_grad=True)
tensor([-0.1414], requires_grad=True)


In [ ]:
y_hat = W @ X.T + b
print(y_hat)
print(y_true)

tensor([[-1.2151,  0.5532,  0.1286,  0.5462, -0.0146,  2.5002, -0.6058,  0.7986,
          0.2773, -2.6856]], grad_fn=<AddBackward0>)
tensor([[ 2.9767],
        [-0.3626],
        [ 0.6136],
        [-0.3170],
        [ 0.8478],
        [-3.8200],
        [ 1.9563],
        [-0.7541],
        [ 0.1869],
        [ 5.4388]])


In [ ]:
lr, epochs = 0.01, 100

W, b = torch.randn(1, 1, requires_grad= True), torch.randn(1, requires_grad = True)

for epoch in range(epochs):

    y_hat = w @ x

In [33]:
lr, epochs = 0.01, 100

W, b = torch.randn(1, 1, requires_grad = True), torch.randn(1, requires_grad = True)

X = torch.randn(10, 1)

true_w = torch.tensor([2.0])
true_b = torch.tensor(1.0)

y_true = true_w * X + true_b + torch.randn(10, 1) * 0.1

for epoch in range(epochs):
    
    z = X @ W + b

    loss = torch.mean((z - y_true) ** 2)

    loss.backward()

    with torch.no_grad():
        W -= lr - W.grad
        b -= lr - b.grad

    if epoch % 10 == 0:
        print(loss)

    W.grad.zero_()
    b.grad.zero_()


tensor(4.1842, grad_fn=<MeanBackward0>)
tensor(4.7947e+11, grad_fn=<MeanBackward0>)
tensor(2.7520e+23, grad_fn=<MeanBackward0>)
tensor(1.5796e+35, grad_fn=<MeanBackward0>)
tensor(inf, grad_fn=<MeanBackward0>)
tensor(inf, grad_fn=<MeanBackward0>)
tensor(inf, grad_fn=<MeanBackward0>)
tensor(nan, grad_fn=<MeanBackward0>)
tensor(nan, grad_fn=<MeanBackward0>)
tensor(nan, grad_fn=<MeanBackward0>)
